## -*- docker-image-name: "cerebus2/multiproc-example" -*-
# Build from the baseline; ONBUILD triggers will copy project/ and ssh/
# directories into the image, and run pip installs.

FROM cerebus2/swarm-multiproc:base

LABEL maintainer="" \
      description=""

